apiVersion: v1
kind: Secret
metadata:
  name: solidarytech-aws-secret
  namespace: solidarytech
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIA6JVMCNOD564GFSKB"
  AWS_SECRET_ACCESS_KEY: "QNZSJliL4eXSll62s2+my8DNkbTKGKCZJb/5OsYE"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEC8aCXVzLXdlc3QtMiJIMEYCIQC6vytPExb2Rfa/Uf8mtVscYxMNInW5Tqj1MvN/GAgAVwIhAJ+JQXA5HP1SDMzGlS4Mn86oKN6KAzuCtsmCVGEOhjIsKrwCCPj//////////wEQAhoMOTgyODM0NjM3NzAzIgy2LgwAidOsZFuoJRsqkAKHkYTFu8CcndLaL3jcEYIDYcknj1WynCkLhLIQZY7o0AwLfyUKAwFawY1uEt9xygqfSlk+Bh+ft1CPnZFM/VKXUNdvMbGL91ewGE0OsfuWtcaLrCHjB0EsbfFFL86n/GiDWQu2lb1YQNXqh8XiFC4srR91okbeNKK941T3tIkcenVwzBG+aczZE5xpvnYeToj2CGtM0332keEU2W922rtFEKcR6DOataP3UqGG7vEwu1K1f/MIifcspBWI+oSwvyTsXwxeBZtaGMrPKD4O11ff5D+9hmd7lO5D5zncq4IMK03bsgLIyZSa1RgBvb7963yxhdmw5KffPdTCLo6IP4PCvLi5pjlCRaTOE30pbIOOBTDz2OHRBjqcAeX21HK79UIO5Jdoyd5DrFvDb0pNHVWS6WQWz8l0BkJL/NNFnq4HD+2uf2IaTOs2+2i2cJ9cb6rnWbDyURNuxDYeLQcnlxbxH+BSRrm99qrJ0FWhwqtxidkHQ2obafiYyU/zJ7Yz/EpBeHpfi8Y1Ib4WfwMAjr6SCs4lfXPhGYHkbkDSHJd0e+0nNBPWOmqBpVlgjgHbhozuTkSh9Q=="
