apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-service
  namespace: solidarytech
  labels:
    app: donation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donation-service
  template:
    metadata:
      labels:
        app: donation-service
    spec:
      containers:
        - name: app
          image: traefik/whoami:latest
          args: [ "--port", "8082" ]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 2
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: solidarytech
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: donation-service
